version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8502"
    environment:
      RELEASE: DEV
    volumes:
      - ./src/models:/usr/src/app/models
      - ./.streamlit:/usr/src/app/.streamlit